In [3]:
print("hello world")

hello world


In [4]:
words = open("names.txt", "r").read().splitlines()

In [5]:
words[:10]

['emma',
 'olivia',
 'ava',
 'isabella',
 'sophia',
 'charlotte',
 'mia',
 'amelia',
 'harper',
 'evelyn']

In [6]:
len(words)

32033

In [7]:
min(len(w) for w in words)

2

In [8]:
max(len(w) for w in words)

15

In [9]:
b = {}
for w in words:
    chs = ['<S>'] + list(w) + ['<E>']
    for ch1, ch2 in zip(chs, chs[1:]):
        bigram = (ch1, ch2)
        b[bigram] = b.get(bigram, 0) + 1

In [10]:
sorted(b.items(), key=lambda x: x[1], reverse=True)[:10]

[(('n', '<E>'), 6763),
 (('a', '<E>'), 6640),
 (('a', 'n'), 5438),
 (('<S>', 'a'), 4410),
 (('e', '<E>'), 3983),
 (('a', 'r'), 3264),
 (('e', 'l'), 3248),
 (('r', 'i'), 3033),
 (('n', 'a'), 2977),
 (('<S>', 'k'), 2963)]

In [11]:
import torch

In [12]:
N = torch.zeros((27, 27), dtype=torch.int32)

In [13]:
chars = sorted(list(set(''.join(words))))
stoi = {s: i+1 for i, s in enumerate(chars)}
stoi['.'] = 0
stoi

{'a': 1,
 'b': 2,
 'c': 3,
 'd': 4,
 'e': 5,
 'f': 6,
 'g': 7,
 'h': 8,
 'i': 9,
 'j': 10,
 'k': 11,
 'l': 12,
 'm': 13,
 'n': 14,
 'o': 15,
 'p': 16,
 'q': 17,
 'r': 18,
 's': 19,
 't': 20,
 'u': 21,
 'v': 22,
 'w': 23,
 'x': 24,
 'y': 25,
 'z': 26,
 '.': 0}

In [14]:
for w in words:
    chs = ['<S>'] + list(w) + ['<E>']
    for ch1, ch2 in zip(chs, chs[1:]):
        bigram = (ch1, ch2)
        b[bigram] = b.get(bigram, 0) + 1

In [15]:
list(w)

['z', 'z', 'y', 'z', 'x']

In [16]:
xs, ys = [], []
for w in words[:1]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        print(ch1, ch2)
        xs.append(ix1)
        ys.append(ix2)
        
xs = torch.tensor(xs)
ys = torch.tensor(ys)

. e
e m
m m
m a
a .


In [20]:
xs

tensor([ 0,  5, 13, 13,  1])

In [21]:
ys

tensor([ 5, 13, 13,  1,  0])

In [30]:
import torch.nn.functional as F
xenc = F.one_hot(xs, num_classes=27).float()
xenc

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
xenc.shape

torch.Size([5, 27])

In [31]:
W = torch.randn((27, 27))
xenc @ W

tensor([[-0.4048, -0.2054, -0.8357,  0.0192,  0.2512,  0.4579,  0.8275, -1.6260,
          0.5114,  0.6243, -0.1792, -0.3709,  1.3187, -2.1515, -0.2267,  1.4216,
         -1.0851,  0.0524, -0.9238, -0.5012,  1.2717, -0.4840,  0.3305,  1.2369,
         -0.5296,  0.0331, -0.7057],
        [-0.7008,  0.2359, -0.7835,  0.4746,  0.6267, -0.8703,  0.1164, -0.9895,
         -0.8246, -0.5627, -0.9699, -0.4478, -0.5193,  0.7321, -2.1382,  1.1043,
         -0.2992,  0.1567, -0.9187, -0.9047,  1.6717,  2.0008,  1.5577,  0.9088,
          0.4267,  0.4277,  0.3547],
        [ 0.4448,  1.4080, -0.7480, -1.3632, -0.9442,  1.1682, -1.9845, -1.2726,
         -0.5320, -0.1963, -0.4410, -0.4276,  0.4740,  0.3307,  1.0032, -0.7067,
          0.9092,  0.5817,  2.2310, -0.2338, -0.2695, -0.1012,  0.6823,  0.1261,
         -0.0900,  0.0771,  0.5406],
        [ 0.4448,  1.4080, -0.7480, -1.3632, -0.9442,  1.1682, -1.9845, -1.2726,
         -0.5320, -0.1963, -0.4410, -0.4276,  0.4740,  0.3307,  1.0032, -0.7067

In [ ]:
logits = (xenc @ W) # log-counts that correspond to each possible next character, but has negative values
counts = logits.exp() # counts which are all positive which is ready for normalization
probs = counts / counts.sum(1, keepdim=True) # normalization
probs

tensor([[0.0187, 0.0228, 0.0122, 0.0286, 0.0360, 0.0443, 0.0641, 0.0055, 0.0467,
         0.0523, 0.0234, 0.0193, 0.1048, 0.0033, 0.0223, 0.1162, 0.0095, 0.0295,
         0.0111, 0.0170, 0.1000, 0.0173, 0.0390, 0.0966, 0.0165, 0.0290, 0.0138],
        [0.0116, 0.0297, 0.0107, 0.0377, 0.0439, 0.0098, 0.0264, 0.0087, 0.0103,
         0.0134, 0.0089, 0.0150, 0.0140, 0.0488, 0.0028, 0.0708, 0.0174, 0.0275,
         0.0094, 0.0095, 0.1249, 0.1736, 0.1115, 0.0583, 0.0360, 0.0360, 0.0335],
        [0.0370, 0.0969, 0.0112, 0.0061, 0.0092, 0.0762, 0.0033, 0.0066, 0.0139,
         0.0195, 0.0153, 0.0155, 0.0381, 0.0330, 0.0646, 0.0117, 0.0588, 0.0424,
         0.2207, 0.0188, 0.0181, 0.0214, 0.0469, 0.0269, 0.0217, 0.0256, 0.0407],
        [0.0370, 0.0969, 0.0112, 0.0061, 0.0092, 0.0762, 0.0033, 0.0066, 0.0139,
         0.0195, 0.0153, 0.0155, 0.0381, 0.0330, 0.0646, 0.0117, 0.0588, 0.0424,
         0.2207, 0.0188, 0.0181, 0.0214, 0.0469, 0.0269, 0.0217, 0.0256, 0.0407],
        [0.0403, 0.0037,

In [34]:
probs[0].sum()

tensor(1.)

In [36]:
# Summary -------------- >>>>>

In [37]:
xs

tensor([ 0,  5, 13, 13,  1])

In [38]:
ys

tensor([ 5, 13, 13,  1,  0])

In [39]:
# randomly initialize 27 neurons' weights, each neuron receive 27 inputs
g = torch.Generator().manual_seed(2147483647)
W = torch.randn((27, 27), generator=g)

In [ ]:
# forward pass
xenc = F.one_hot(xs, num_classes=27).float() # input to the network: one-hot encoding
logits = xenc @ W # log-counts that correspond to each possible next character, but has negative values
counts = logits.exp() # counts which are all positive which is ready for normalization
probs = counts / counts.sum(1, keepdim=True) # normalization
# the last 2 lines here are together called "softmax!"

In [45]:
probs.shape

torch.Size([5, 27])

In [ ]:
nlls = torch.zeros(5) 